// Code generated by protoc-gen-go. DO NOT EDIT.
// source: merkeltrie.proto

package protocol

import proto "github.com/bumoproject/bumo-sdk-go/src/common/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CHILDTYPE int32

const (
	CHILDTYPE_NONE  CHILDTYPE = 0
	CHILDTYPE_INNER CHILDTYPE = 1
	CHILDTYPE_LEAF  CHILDTYPE = 2
)

var CHILDTYPE_name = map[int32]string{
	0: "NONE",
	1: "INNER",
	2: "LEAF",
}
var CHILDTYPE_value = map[string]int32{
	"NONE":  0,
	"INNER": 1,
	"LEAF":  2,
}

func (x CHILDTYPE) String() string {
	return proto.EnumName(CHILDTYPE_name, int32(x))
}
func (CHILDTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_merkeltrie_df6403cae375ea02, []int{0}
}

type Child struct {
	Sublocation          []byte    `protobuf:"bytes,1,opt,name=sublocation,proto3" json:"sublocation,omitempty"`
	Hash                 []byte    `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Childtype            CHILDTYPE `protobuf:"varint,3,opt,name=childtype,enum=protocol.CHILDTYPE" json:"childtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Child) Reset()         { *m = Child{} }
func (m *Child) String() string { return proto.CompactTextString(m) }
func (*Child) ProtoMessage()    {}
func (*Child) Descriptor() ([]byte, []int) {
	return fileDescriptor_merkeltrie_df6403cae375ea02, []int{0}
}
func (m *Child) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Child.Unmarshal(m, b)
}
func (m *Child) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Child.Marshal(b, m, deterministic)
}
func (dst *Child) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Child.Merge(dst, src)
}
func (m *Child) XXX_Size() int {
	return xxx_messageInfo_Child.Size(m)
}
func (m *Child) XXX_DiscardUnknown() {
	xxx_messageInfo_Child.DiscardUnknown(m)
}

var xxx_messageInfo_Child proto.InternalMessageInfo

func (m *Child) GetSublocation() []byte {
	if m != nil {
		return m.Sublocation
	}
	return nil
}

func (m *Child) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Child) GetChildtype() CHILDTYPE {
	if m != nil {
		return m.Childtype
	}
	return CHILDTYPE_NONE
}

type Node struct {
	Children             []*Child `protobuf:"bytes,1,rep,name=children" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_merkeltrie_df6403cae375ea02, []int{1}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetChildren() []*Child {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*Child)(nil), "protocol.Child")
	proto.RegisterType((*Node)(nil), "protocol.Node")
	proto.RegisterEnum("protocol.CHILDTYPE", CHILDTYPE_name, CHILDTYPE_value)
}

func init() { proto.RegisterFile("merkeltrie.proto", fileDescriptor_merkeltrie_df6403cae375ea02) }

var fileDescriptor_merkeltrie_df6403cae375ea02 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x4d, 0x2d, 0xca,
	0x4e, 0xcd, 0x29, 0x29, 0xca, 0x4c, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0xc9, 0xf9, 0x39, 0x4a, 0x05, 0x5c, 0xac, 0xce, 0x19, 0x99, 0x39, 0x29, 0x42, 0x0a, 0x5c, 0xdc,
	0xc5, 0xa5, 0x49, 0x39, 0xf9, 0xc9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x3c, 0x41, 0xc8, 0x42, 0x42, 0x42, 0x5c, 0x2c, 0x19, 0x89, 0xc5, 0x19, 0x12, 0x4c, 0x60, 0x29,
	0x30, 0x5b, 0xc8, 0x90, 0x8b, 0x33, 0x19, 0xa4, 0xbd, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x59, 0x81,
	0x51, 0x83, 0xcf, 0x48, 0x58, 0x0f, 0x66, 0xb8, 0x9e, 0xb3, 0x87, 0xa7, 0x8f, 0x4b, 0x48, 0x64,
	0x80, 0x6b, 0x10, 0x42, 0x95, 0x92, 0x31, 0x17, 0x8b, 0x5f, 0x7e, 0x4a, 0xaa, 0x90, 0x36, 0x17,
	0x07, 0x58, 0xb0, 0x28, 0x15, 0x64, 0x1b, 0xb3, 0x06, 0xb7, 0x11, 0x3f, 0x92, 0x4e, 0x90, 0x4c,
	0x10, 0x5c, 0x81, 0x96, 0x16, 0x17, 0x27, 0xdc, 0x30, 0x21, 0x0e, 0x2e, 0x16, 0x3f, 0x7f, 0x3f,
	0x57, 0x01, 0x06, 0x21, 0x4e, 0x2e, 0x56, 0x4f, 0x3f, 0x3f, 0xd7, 0x20, 0x01, 0x46, 0x90, 0xa0,
	0x8f, 0xab, 0xa3, 0x9b, 0x00, 0x53, 0x12, 0x1b, 0xd8, 0x14, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x00, 0xa0, 0x7b, 0xbd, 0xf7, 0x00, 0x00, 0x00,
}
